<!-- NEW HOMEWORK -->

<div id="newHomework" class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Tilføj lektier</h4>
            </div>
            <div class="modal-body">
                <?php include("inc/forms/homework.php"); ?>
            </div>
        </div>
    </div>
</div>

<!-- NEW EVENT -->

<div id="newEvent" class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class='modal-title'>Tilføj ny begivenhed</h4>
            </div>
            <div class="modal-body">
                <?php include("inc/forms/events.php"); ?>
            </div>
        </div>
    </div>
</div>

<!-- NEW WORKOUT -->

<div id="newWorkout" class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Tilføj træningspas</h4>
            </div>
            <div class="modal-body">
                <?php include("inc/forms/workouts.php"); ?>
            </div>
        </div>
    </div>
</div>

<!-- NEW JOURNAL ENTRY -->

<div id="newJournal" class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Logbog</h4>
            </div>
            <div class="modal-body">
                <?php include("inc/forms/journal.php"); ?>
            </div>
        </div>
    </div>
</div>

<!-- NEW TO-DO -->

<div id="newToDo" class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Tilføj opgave</h4>
            </div>
            <div class="modal-body">
                <?php include("inc/forms/to-do.php"); ?>
            </div>
        </div>
    </div>
</div>