<div class="row">
    <div class="col-lg-12">
        <div class="btn-group btn-group-justified">
            <a class="btn btn-primary" data-target="#newHomework" data-toggle="modal"><i class="fa fa-book fa-lg fa-fw"></i> Lektier</a>
            <a class="btn btn-primary" data-target="#newWorkout" data-toggle="modal"><i class="fa fa-trophy fa-lg fa-fw"></i> Træning</a>
        </div>
    </div>
</div>
<br/>
<div class="row">
    <div class="col-lg-12">
        <div class="btn-group btn-group-justified">
            <a class="btn btn-primary" data-target="#newEvent" data-toggle="modal"><i class="fa fa-star fa-lg fa-fw"></i> Begivenheder</a>
            <a class="btn btn-primary" data-target="#newToDo" data-toggle="modal"><i class="fa fa-check-square-o fa-lg fa-fw"></i> To-Do</a>
        </div>
    </div>
</div>
<br/>
<table id="minical" class="table table-condensed table-striped table-center table-equal table-bordered">
    <thead>
        <tr>
            <th>Man</th>
            <th>Tir</th>
            <th>Ons</th>
            <th>Tor</th>
            <th>Fre</th>
            <th>Lør</th>
            <th>Søn</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class='text-muted'>1</td>
            <td class='text-muted'>2</td>
        </tr>
        <tr>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td class='text-muted'>8</td>
            <td class='text-muted'>9</td>
        </tr>
        <tr>
            <td>10</td>
            <td><strong>20</strong></td>
            <td>12</td>
            <td>13</td>
            <td>14</td>
            <td class='text-muted'>15</td>
            <td class='text-muted'>16</td>
        </tr>
        <tr>
            <td>17</td>
            <td>18</td>
            <td>19</td>
            <td>20</td>
            <td>21</td>
            <td class='text-muted'>22</td>
            <td class='text-muted'>23</td>
        </tr>
        <tr>
            <td>24</td>
            <td>25</td>
            <td>26</td>
            <td>27</td>
            <td>28</td>
            <td class='text-muted'>29</td>
            <td class='text-muted'>30</td>
        </tr>
    </tbody>
</table>

<a class="btn btn-primary btn-block" href="/logout.php"><i class="fa fa-power-off"></i> Log af</a>
